import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import {mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import {Chess,START_FEN} from '../src/xiangqi.mjs';
const out='test-results';mkdirSync(out,{recursive:true});
const browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader']});
const context=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true});
const page=await context.newPage(),errors=[];
page.on('pageerror',e=>errors.push(e.message));
const state=()=>page.evaluate(()=>JSON.parse(window.render_game_to_text()));
const finished=()=>page.waitForFunction(()=>{const s=JSON.parse(window.render_game_to_text());return s.ready&&!s.busy;},{},{timeout:60000});
const clickSquare=s=>page.locator(`[data-square="${s}"]`).click();
const load=async fen=>{await page.locator('#fen-input').fill(fen);await page.locator('#load-fen').click();await finished();};
try{
 await page.goto(process.env.FLY_TEST_URL||'http://localhost:5188');await finished();
 assert.equal(await page.locator('[data-square]').count(),90);assert.equal(await page.locator('#board .piece').count(),32);
 await page.screenshot({path:`${out}/desktop-initial.png`,fullPage:true});
 const requests=[];page.on('request',r=>requests.push(r.url()));await context.setOffline(true);
 await clickSquare('e3');assert.deepEqual((await state()).legalTargets,['e4']);
 await clickSquare('d3');assert.equal((await state()).fen,START_FEN);
 await clickSquare('e3');await clickSquare('e4');await finished();
 assert.deepEqual((await state()).history,['兵五进一','砲2平1']);
 assert.equal(await page.locator('#spikes').innerText(),'6,108');
 await page.screenshot({path:`${out}/desktop-play.png`,fullPage:true});
 const download=page.waitForEvent('download');await page.locator('#export').click();await (await download).saveAs(`${out}/trial.json`);
 const record=JSON.parse(readFileSync(`${out}/trial.json`)).trial;
 assert.equal(record.totalSpikes,record.events.length/2);assert.equal(record.selected.uci,'b7a7');assert(record.signalNorm>0);
 const before=(await state()).fen;await page.locator('#ablate').click();await finished();assert.equal((await state()).fen,before);
 assert.match(await page.locator('#ablation-result').innerText(),/因果作用/);
 const auditDownload=page.waitForEvent('download');await page.locator('#export-audit').click();await (await auditDownload).saveAs(`${out}/audit.json`);
 const audit=JSON.parse(readFileSync(`${out}/audit.json`)).audit;assert.equal(audit.disconnected.signalNorm,0);assert.equal(audit.disconnected.selected,null);assert(audit.intact.signalNorm>0);
 assert.deepEqual(requests,[]);
 await page.locator('#replay').click();assert.match(await page.locator('#phase').innerText(),/回放/);await page.locator('#replay').click();
 await page.locator('#undo').click();assert.equal((await state()).fen,START_FEN);
 await page.locator('#flip').click();assert.equal(await page.locator('[data-square]').first().getAttribute('data-square'),'i0');await clickSquare('h2');assert((await state()).legalTargets.includes('e2'));await page.locator('#flip').click();
 await page.locator('#side').selectOption('b');await finished();assert.equal((await state()).turn,'black');assert.equal((await state()).history.length,1);
 await page.locator('#side').selectOption('w');await finished();
 await page.getByText('载入自定义棋局（FEN）',{exact:true}).click();
 await load('R3k4/4R4/9/9/9/9/9/9/9/4K4 b - - 0 1');assert((await state()).gameOver);assert.match((await state()).status,/将死，你赢/);assert.equal(await page.locator('.in-check').count(),1);
 await load('4k4/3R1R3/9/9/4P4/9/9/9/9/4K4 b - - 0 1');assert.match((await state()).status,/困毙.*你赢/);
 const terminal=(await state()).fen;await load('invalid');assert.equal((await state()).fen,terminal);assert.match((await state()).status,/无法载入/);
 // Human move creates mate; no network turn should be attempted afterward.
 await load('4k4/R2R5/9/9/4P4/9/9/9/9/4K4 w - - 0 1');
 await clickSquare('a8');await clickSquare('a9');await finished();
 assert((await state()).gameOver);assert.match((await state()).status,/将死，你赢/);assert.equal((await state()).history.length,1);
 await page.locator('#new-game').click();await finished();
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>window.scrollTo(0,0));
 await page.screenshot({path:`${out}/mobile.png`,fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await clickSquare('h2');await clickSquare('e2');await finished();assert.equal((await state()).history[0],'炮二平五');assert.equal((await state()).history.length,2);
 await page.screenshot({path:`${out}/mobile-play.png`,fullPage:true});
 assert(new Chess((await state()).fen));
 await context.setOffline(false);
 const broken=await browser.newContext();await broken.route('**/data/neurons.bin.gz',route=>route.fulfill({body:'corrupt graph',contentType:'application/octet-stream'}));
 const tab=await broken.newPage();await tab.goto(process.env.FLY_TEST_URL||'http://localhost:5188');await tab.waitForFunction(()=>!document.getElementById('retry-load').hidden,{},{timeout:60000});assert.match(await tab.locator('#loading-help').innerText(),/校验失败/);assert(await tab.locator('#new-game').isDisabled());
 assert.deepEqual(errors,[]);
 const summary={desktop:true,mobileWidth:390,offlineMoveAndAblation:true,legalNeuralReply:record.selected,undo:true,flip:true,playBlack:true,checkmate:true,stalemateLoss:true,invalidFenPreservesBoard:true,corruptDataFailsClosed:true,browserErrors:errors};
 writeFileSync(`${out}/browser-check.json`,JSON.stringify(summary,null,2));console.log(JSON.stringify(summary,null,2));
}finally{await browser.close();}
