import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {readFileSync,statSync,mkdirSync} from 'node:fs';
const base=process.env.TEST_URL||'http://127.0.0.1:5277';
mkdirSync('test-results/world',{recursive:true});
const browser=await chromium.launch({headless:true});
try {
  const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base+'/');
  assert.match(await page.title(),/蝇境/);
  assert.equal(await page.locator('#board').count(),0);
  assert.doesNotMatch(await page.locator('body').innerText(),/蝇弈|中国象棋|开始对弈/);
  await page.waitForFunction(()=>window.render_game_to_text&&JSON.parse(window.render_game_to_text()).neural?.windows>=3,{},{timeout:120000});
  await page.screenshot({path:'test-results/world/home.png',fullPage:true});
  await page.click('#pause');await page.waitForFunction(()=>!JSON.parse(window.render_game_to_text()).inflight);
  const read=()=>page.evaluate(()=>JSON.parse(window.render_game_to_text()));
  const before=await read();await page.waitForTimeout(500);assert.equal((await read()).world.time,before.world.time);
  await page.locator('#light').fill('15');await page.locator('#light').dispatchEvent('input');await page.click('#food');await page.click('#camera');
  assert.equal((await read()).world.light,.15);assert.notDeepEqual((await read()).world.food,before.world.food);assert.equal(await page.locator('#camera').getAttribute('aria-pressed'),'true');
  await page.click('#pause');
  await page.waitForFunction(()=>JSON.parse(window.render_game_to_text()).clips>0,{},{timeout:240000});
  const planEvent=page.waitForEvent('download');await page.click('#export');await (await planEvent).saveAs('test-results/world/browser-plan.json');
  const plan=JSON.parse(readFileSync('test-results/world/browser-plan.json'));assert.ok(plan.clips.length>0);
  await page.click('#record');await page.waitForTimeout(1800);
  const mediaEvent=page.waitForEvent('download');await page.click('#record');await (await mediaEvent).saveAs('test-results/world/sample.webm');assert.ok(statSync('test-results/world/sample.webm').size>1000);
  await page.setInputFiles('#videos',['test-results/world/sample.webm']);await page.waitForFunction(()=>document.getElementById('player').currentTime>0);
  await page.setViewportSize({width:390,height:844});await page.waitForTimeout(300);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({path:'test-results/world/mobile-home.png',fullPage:true});assert.deepEqual(errors,[]);
  console.log(JSON.stringify({home:'fly-world',noChess:true,pause:true,controls:true,clips:plan.clips.length,recording:true,playback:true,mobile:true,errors}));
} finally {await browser.close();}
